name: GitHub Classroom Workflow

  on: [push]

  jobs:
    build:
      name: Autograding
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check out tests private repo
          uses: actions/checkout@master
          with:
            repository: TFS22QA/qa_fullstack_123_tests
            token: ${{ secrets.my_pat }}
        - uses: education/autograding@v1