name: MyActionsWF
on: [push]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TFS22QA/qa_fullstack_123_tests
          token: ${{ secrets.MY_PAT }}
      - uses: education/autograding@v1
